name: CI/CD Pipeline Node.js 18

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test Node
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Configurer Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Installer les dependances
        run: npm install

      - name: Lancer les tests (si existants)
        run: npm test --if-present

      - name: Sauvegarder les fichiers (si necessaire)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-files
          path: .

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    # Correction ici : on utilise 'main' au lieu de 'master'
    if: github.ref == 'refs/heads/main' 

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Connexion a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et Push de l'image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest
