name: CI/CD Pipeline Node.js 18

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Étape 1 : Installation et Tests
  build:
    name: Build & Test Node
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Configurer Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Installer les dependances
        run: npm install

      - name: Lancer les tests (si existants)
        run: npm test --if-present

  # Étape 2 : Création de l'image Docker
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' 

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Connexion a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et Push de l'image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

  # Étape 3 : Scan de sécurité (Contrainte C14)
  security_scan:
    name: Scan Image with Trivy
    runs-on: ubuntu-latest
    needs: docker  # S'exécute IMPÉRATIVEMENT après le job docker

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Lancer Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/node-app:latest'
          format: 'table'
          severity: 'HIGH,CRITICAL' # Contrainte : Détecter uniquement HIGH et CRITICAL
          exit-code: '0' # Fait échouer le pipeline en cas de faille trouvée
